inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7

Naming/MethodParameterName:
  AllowedNames: ["x", "y", "z"]

RSpec/EmptyLineAfterHook:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/sentry-gruf.rb

Lint/RescueException:
  Enabled: false

Style/NilLambda:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: e

Style/HashConversion:
  Exclude:
    - spec/**/*_spec.rb
